# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-lts-latest
  tools:
    python: "3.12"
  commands:
    - pip install -r docs/requirements.txt
    - sphinx-build -b html -D language=zh docs/source $READTHEDOCS_OUTPUT/html
    - sphinx-build -b html -D language=en docs/source $READTHEDOCS_OUTPUT/html/en

